site_name: Eglinux
site_url: https://www.eglinux.com
site_author: Eglinux
edit_uri: edit/main/docs/
site_description: >-
  Eglinux 的个人网站，记录生活，分享技术！

# Repository
repo_name: eglinuxer/eglinux
repo_url: https://github.com/eglinuxer/eglinux
theme:
  name: material
  logo: assets/logo.svg
  custom_dir: overrides
  icon:
    edit: material/pencil
    view: material/eye
  font:
    text: Roboto
    code: Roboto Mono
  language: zh
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune
    - navigation.indexes
    # - navigation.sections
    # - navigation.expand
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    # - content.code.select
    # - header.autohide
    - announce.dismiss
    # - navigation.footer
    - content.action.edit
    - content.action.view
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: indigo
      accent: deep orange

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: indigo
      accent: deep orange

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: indigo
      accent: yellow

plugins:
  # - privacy # 目前如果启用，搜索框就会不能显示
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - social:
      # debug: true
      # debug_color: yellow
      cards_layout: custom
      cards_layout_options:
          # background_color: "#759EC8"
          background_color: "#0075D858"
          background_image: layouts/background.png
          font_family: Noto Sans SC
  - privacy:
      links_attr_map:
        target: _blank
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: eglinuxer/eglinux
      branch: main

extra:
  homepage: https://www.eglinux.com
  consent:
    title: Cookie 声明
    description: >-
      我们使用 Cookie 来识别您的重复访问和偏好设置，以及衡量我们文档的有效性和用户是否找到他们正在搜索的内容。在您同意的情况下，您将帮助我们改进我们的文档。</br></br>

      Cookie 是一小段文本信息，由您访问网站时存储在您的计算机或设备上的。它们包含以下信息：</br></br>

      1. 认证信息：用于识别您的登录状态和身份验证。</br>
      2. 偏好设置：用于保存您的个性化设置，例如语言偏好、字体大小等。</br>
      3. 访问统计：用于收集匿名的访问数据，以便我们评估文档的使用情况和改进方向。</br></br>

      我们保证在使用 Cookie 时尊重您的隐私权，并且不会收集任何个人身份信息。您可以随时在浏览器设置中管理和删除这些 Cookie。</br></br>

      请注意，我们只会在您明确同意的情况下使用 Cookie。您可以根据自己的偏好设置浏览器以拒绝接受 Cookie。如果您选择禁用 Cookie，可能会影响您访问我们网站的某些功能。</br></br>

      如果您对我们使用 Cookie 的方式有任何疑问或需要更多信息，请随时联系我们。

    actions:
      - accept
      - manage
      - reject
  social:
    - icon: simple/github
      name: GitHub
      link: https://github.com/eglinuxer
    - icon: simple/zhihu
      name: 知乎
      link: https://www.zhihu.com/people/eglinux
    - icon: simple/bilibili
      name: B站
      link: https://space.bilibili.com/448334347
  generator: false
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: 该页面是否有用?
      ratings:
        - icon: material/emoticon-happy-outline
          name: 非常有用
          data: 1
          note: 感谢您的反馈！
        - icon: material/emoticon-sad-outline
          name: 有待改进
          data: 0
          note: >-
            感谢您的反馈！请通过 <a href="https://github.com/eglinuxer/eglinux/issues/new/?title=[页面问题反馈]+{title}+-+{url}" target=_blank>Github issues</a> 告诉我改进建议。


markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      permalink_title: 跳转到此部分目录

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

nav:
  - 主页:
    - index.md
  - CMake:
    - cmake/index.md
    - 基础教程:
      - cmake/basic/index.md
      - 第 1 步 [一个简单的起点]: cmake/basic/01_a_basic_starting_point.md
      - 第 2 步 [添加一个库]: cmake/basic/02_adding_a_library.md
      - 第 3 步 [为库添加使用要求]: cmake/basic/03_adding_usage_requirements_for_a_library.md
      - 第 4 步 [添加生成表达式]: cmake/basic/04_adding_generator_expressions.md
      - 第 5 步 [安装和测试]: cmake/basic/05_installing_and_testing.md
      - 第 6 步 [添加测试看板支持]: cmake/basic/06_adding_support_for_a_testing_dashboard.md
      - 第 7 步 [添加系统分析]: cmake/basic/07_adding_system_introspection.md
      - 第 8 步 [自定义命令和生成文件]: cmake/basic/08_adding_a_custom_gommand_and_generated_file.md
      - 第 9 步 [打包安装程序]: cmake/basic/09_packaging_an_installer.md
      - 第 10 步 [选择静态库或共享库]: cmake/basic/10_selecting_static_or_shared_libraries.md
      - 第 11 步 [添加导出配置]: cmake/basic/11_adding_export_configuration.md
      - 第 12 步 [打包调试和发布版本]: cmake/basic/12_packaging_debug_and_release.md
    - CMake 命令:
      - cmake/cmd/index.md
  - Linux:
    - linux/index.md
  - C/C++:
    - ccplus/index.md
  - Python:
    - python/index.md
  - Qt:
    - qt/index.md
  - Lua:
    - lua/index.md


copyright: >
  Copyright &copy; 2023 - 2024 Eglinux –
  <a href="#__consent">更改 Cookie 设置</a>
