site_name: Eglinux
site_url: https://www.eglinux.com/
repo_name: eglinuxer/eglinux
repo_url: https://github.com/eglinuxer/eglinux
site_author: Eglinux
edit_uri: edit/main/docs/
site_description: >-
  Eglinux 的个人网站，记录生活，分享技术！

# Copyright
copyright: Copyright &copy; 2023 - 2024 Eglinux

theme:
  name: material
  custom_dir: overrides
  language: zh
  logo: assets/favicon-16x16.png
  favicon: assets/images/favicon.ico
  font:
    text: Noto Serif Simplified Chinese
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.footnote.tooltips

plugins:
  - search
  - glightbox

  # Continuous integration
  - group:
      enabled: !ENV CI
      plugins:
        - git-revision-date-localized:
            enable_creation_date: true
            type: timeago
        - git-committers:
            repository: eglinuxer/eglinux
            token: !ENV GH_TOKEN
        - optimize
        - projects

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  homepage: https://www.eglinux.com
  generator: false
  social:
    - icon: simple/github
      name: GitHub
      link: https://github.com/eglinuxer
    - icon: simple/zhihu
      name: 知乎
      link: https://www.zhihu.com/people/eglinux
    - icon: simple/bilibili
      name: B站
      link: https://space.bilibili.com/448334347
  annotate:
    json: [.s2]

nav:
  - 首页: index.md
  - Eglinux:
    - eglinux/index.md
    - 简历: eglinux/resume.md
    - 动态: eglinux/active.md
    - 读书: eglinux/book.md
    - 课程: eglinux/course.md
    - 赞助: eglinux/support_me.md
  - Linux:
    - linux/index.md
  - Python:
    - python/index.md
    - Python 书籍:
      - python/mastering_python.md
    - Python 开发环境:
      - python/env.md
  - C/C++:
    - ccplusplus/index.md
  - CMake:
    - cmake/index.md
  - Qt:
    - qt/index.md
  - Lua:
    - lua/index.md