site_name: Eglinux
theme:
  name: material
  language: zh
  logo: assets/favicon-16x16.png
  favicon: assets/images/favicon.ico
  font:
    text: Noto Serif Simplified Chinese
    code: Roboto Mono

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference

extra:
  homepage: https://www.eglinux.com