site_name: Eglinux
theme:
  name: material
  logo: assets/logo.svg
  custom_dir: overrides
  font:
    text: Roboto
    code: Roboto Mono
  language: zh
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune
    - navigation.indexes
    # - navigation.sections
    # - navigation.expand
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: indigo
      accent: deep orange

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: indigo
      accent: deep orange

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: indigo
      accent: yellow

plugins:
  # - privacy # 目前如果启用，搜索框就会不能显示
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

extra:
  homepage: https://www.eglinux.com
  consent:
    title: Cookie 声明
    description: >-
      我们使用 Cookie 来识别您的重复访问和偏好设置，以及衡量我们文档的有效性和用户是否找到他们正在搜索的内容。在您同意的情况下，您将帮助我们改进我们的文档。</br></br>

      Cookie 是一小段文本信息，由您访问网站时存储在您的计算机或设备上的。它们包含以下信息：</br></br>

      1. 认证信息：用于识别您的登录状态和身份验证。</br>
      2. 偏好设置：用于保存您的个性化设置，例如语言偏好、字体大小等。</br>
      3. 访问统计：用于收集匿名的访问数据，以便我们评估文档的使用情况和改进方向。</br></br>

      我们保证在使用 Cookie 时尊重您的隐私权，并且不会收集任何个人身份信息。您可以随时在浏览器设置中管理和删除这些 Cookie。</br></br>

      请注意，我们只会在您明确同意的情况下使用 Cookie。您可以根据自己的偏好设置浏览器以拒绝接受 Cookie。如果您选择禁用 Cookie，可能会影响您访问我们网站的某些功能。</br></br>

      如果您对我们使用 Cookie 的方式有任何疑问或需要更多信息，请随时联系我们。

    actions:
      - accept
      - manage
      - reject
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: 该页面是否有用?
      ratings:
        - icon: material/emoticon-happy-outline
          name: 非常有用
          data: 1
          note: 感谢您的反馈！
        - icon: material/emoticon-sad-outline
          name: 有待改进
          data: 0
          note: >-
            感谢您的反馈！请通过 <a href="https://github.com/eglinuxer/eglinux/issues/new/?title=[Feedback]+{title}+-+{url}" target=_blank> 告诉我改进建议</a>。
                     
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

nav:
  - 主页:
    - index.md
  - CMake:
    - cmake/index.md
    - 基础教程:
      - cmake/basic/index.md
    - CMake 命令:
      - cmake/cmd/index.md


copyright: >
  Copyright &copy; 2023 - 2024 Eglinux –
  <a href="#__consent">更改 Cookie 设置</a>
